version: '2'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/schuum
      - SPRING_DATASOURCE_USERNAME=schuumadmin
      - SPRING_DATASOURCE_PASSWORD=i<3Beer
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
    ports:
      - "8080:8080"
    expose:
      - "8080"

  db:
    image: 'postgres:15'
    container_name: db
    environment:
      - POSTGRES_USER=schuumadmin
      - POSTGRES_PASSWORD=i<3Beer
      - POSTGRES_DB=schuum
    ports:
      - "5432:5432"
    expose:
      - "5432"

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "81:80"
    expose:
      - "80"